# Setup
title:            Yoncho
tagline:          'A Bounty Hunter Blog'
description:      'Bug Bounty hunter from PerÃº â¤ï¸ğŸ¦™ğŸ‡µğŸ‡ª. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://yoncho14.github.io
baseurl:          ""
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
